# Generated by Django 6.1 on 2026-08-26 04:48

import django.db.models.deletion
import typing
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TenantAuditIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("identity_type", models.CharField(default="user", max_length=32)),
                ("identity_key", models.CharField(blank=True, max_length=255)),
                ("identity_label", models.CharField(blank=True, max_length=255)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("group_names", models.JSONField(blank=True, default=list)),
                ("permission_keys", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("department", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "AUDIT_IDENTITY_MODEL",
                "indexes": [
                    models.Index(
                        fields=["identity_type", "identity_key"],
                        name="swapped_ten_identit_dfc112_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantAuditScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("global", "Global"), ("scoped", "Scoped")],
                        default="global",
                        max_length=20,
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_scopes",
                        to="swapped.tenant",
                    ),
                ),
            ],
            options={
                "swappable": "AUDIT_SCOPE_MODEL",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("scope_type", "global"), ("tenant__isnull", True)
                            ),
                            models.Q(
                                models.Q(("scope_type", "global"), _negated=True),
                                ("tenant__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="swapped_scope_type_and_tenant_agree",
                    ),
                    models.UniqueConstraint(
                        fields=("scope_type", "scope_key"),
                        name="swapped_scope_unique_key_per_type",
                    ),
                ],
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
