# Generated by Django 6.1 on 2026-10-01 01:44

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapped', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantauditidentity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
