# Generated by Django 6.1 on 2026-08-26 04:49

import django.db.models.deletion
import django.utils.timezone
import typing
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Added by hand, and they have to be. The autodetector generated this
        # migration against the models this app ships, where the scope and
        # identity live in this very app -- so it saw nothing to depend on and
        # wrote nothing. The moment a project swaps either model out, the foreign
        # keys below point into *that* project's app, and without these the graph
        # is free to run this migration first and fail with "Related model
        # cannot be resolved".
        #
        # Safe when nothing is swapped: Django ignores a "__first__" dependency
        # that refers to the migration's own app (#22325).
        migrations.swappable_dependency(settings.AUDIT_SCOPE_MODEL),
        migrations.swappable_dependency(settings.AUDIT_IDENTITY_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("identity_type", models.CharField(default="user", max_length=32)),
                ("identity_key", models.CharField(blank=True, max_length=255)),
                ("identity_label", models.CharField(blank=True, max_length=255)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("group_names", models.JSONField(blank=True, default=list)),
                ("permission_keys", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "AUDIT_IDENTITY_MODEL",
            },
        ),
        migrations.CreateModel(
            name="AuditScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("global", "Global"), ("scoped", "Scoped")],
                        default="global",
                        max_length=20,
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                ("_scope", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "swappable": "AUDIT_SCOPE_MODEL",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("_scope", ""), ("scope_type", "global")),
                            models.Q(
                                models.Q(("scope_type", "global"), _negated=True),
                                models.Q(("_scope", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="audit_scope_type_and_value_agree",
                    ),
                    models.UniqueConstraint(
                        fields=("scope_type", "scope_key"),
                        name="audit_scope_unique_key_per_type",
                    ),
                ],
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="AuditAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("content_type_key", models.CharField(blank=True, max_length=255)),
                ("key", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid7, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("action_key", models.CharField(max_length=255)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("global", "Global"), ("scoped", "Scoped")],
                        default="global",
                        max_length=20,
                    ),
                ),
                ("scope_key", models.CharField(blank=True, max_length=255)),
                ("actor_type", models.CharField(max_length=32)),
                ("actor_key", models.CharField(blank=True, max_length=255)),
                ("subject_pk", models.CharField(db_index=True, max_length=255)),
                (
                    "subject_content_type_key",
                    models.CharField(blank=True, max_length=255),
                ),
                ("subject_label", models.CharField(blank=True, max_length=255)),
                ("diff", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUDIT_IDENTITY_MODEL,
                    ),
                ),
                (
                    "on_behalf_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUDIT_IDENTITY_MODEL,
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUDIT_SCOPE_MODEL,
                    ),
                ),
                (
                    "subject_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vinta_audit_logs.auditaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditAffectedIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity_type", models.CharField(max_length=32)),
                ("identity_key", models.CharField(blank=True, max_length=255)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affected_links",
                        to="vinta_audit_logs.audit",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUDIT_IDENTITY_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="audit",
            name="affected_identities",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                through="vinta_audit_logs.AuditAffectedIdentity",
                through_fields=("audit", "identity"),
                to=settings.AUDIT_IDENTITY_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditidentity",
            index=models.Index(
                fields=["identity_type", "identity_key"],
                name="vinta_audit_identit_d9b842_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditaction",
            constraint=models.UniqueConstraint(
                fields=("content_type_key", "key"),
                name="audit_action_unique_key_per_content_type",
            ),
        ),
        migrations.AddIndex(
            model_name="auditaffectedidentity",
            index=models.Index(
                fields=["identity_type", "identity_key", "audit"],
                name="audit_affected_identity_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditaffectedidentity",
            constraint=models.UniqueConstraint(
                fields=("audit", "identity"), name="audit_affected_identity_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                models.F("scope_key"),
                models.OrderBy(models.F("created_at"), descending=True),
                name="audit_scope_recent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                models.F("scope_key"),
                models.F("action_key"),
                models.OrderBy(models.F("created_at"), descending=True),
                name="audit_scope_action_recent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                models.F("scope_key"),
                models.F("actor_type"),
                models.F("actor_key"),
                models.OrderBy(models.F("created_at"), descending=True),
                name="audit_scope_actor_recent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                models.F("scope_key"),
                models.F("subject_content_type_key"),
                models.F("subject_pk"),
                models.OrderBy(models.F("created_at"), descending=True),
                name="audit_scope_subject_recent_idx",
            ),
        ),
    ]
