# Generated by Django 6.1 on 2026-10-01 01:44

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinta_audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='diff',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='auditidentity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
